### ISSUE TITLE
[BUG] Tests fail when ElasticSearch service is running

### ISSUE THREAD

**Issue by BonfaceKilz** [tunapanda/wikonnect#191]
### Describe the bug:
Tests fail after starting  ElasticSearch.

### Expected Behavior
All tests should pass.

### Current Behavior
There are 5 failing tests

### Steps to reproduce
- `systemctl start elasticsearch`
- `yarn test`

### Error Log / Stack Trace (where applicable)

```
  64 passing (12s)
  5 failing

  1) Achievement Awards route and function test
       "before all" hook for "Should GET all Achievement Awards with valid token":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/bonface/Projects/wikonnect/server/test/achievement_awards.spec.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  2) AUTHENTICATION ROUTES
       Auth routes tests: /api/v1/users/
         Should create user on POST requests:

      Uncaught AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 201 but got 400
      + expected - actual

      -400
      +201
      
      at /home/bonface/Projects/wikonnect/server/test/auth.spec.js:54:27
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:797:3)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:990:12)
      at endReadableNT (_stream_readable.js:1204:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)

  3) AUTHENTICATION ROUTES
       Auth routes tests: /api/v1/users/
         Should login a valid user on POST and return token:

      Uncaught AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 400
      + expected - actual

      -400
      +200
      
      at /home/bonface/Projects/wikonnect/server/test/auth.spec.js:91:27
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:797:3)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:990:12)
      at endReadableNT (_stream_readable.js:1204:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)

  4) ACTIVITY ROUTE
       Should CREATE an activity record on POST with valid activityData and return a JSON object:

      Uncaught AssertionError: expected 400 to deeply equal 201
      + expected - actual

      -400
      +201
      
      at /home/bonface/Projects/wikonnect/server/test/routes.spec.js:253:27
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:797:3)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:990:12)
      at endReadableNT (_stream_readable.js:1204:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)

  5) ACTIVITY ROUTE
       Should UPDATE an activity records record on PUT:

      Uncaught AssertionError: expected 400 to deeply equal 201
      + expected - actual

      -400
      +201
      
      at /home/bonface/Projects/wikonnect/server/test/routes.spec.js:304:27
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:797:3)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:990:12)
      at endReadableNT (_stream_readable.js:1204:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)



```
### Tell us about your browser and operating system:
- Operating System: ArchLinux
- NodeJS Version: v12.16.1
- Ember Version: N/A
- ElasticSearch Version: 7.6.1-1
- Postgresql Version: 12.2-1

### Screenshots where applicable

**Comment by BonfaceKilz** [comment]
@mosesokemwa why's the primary key of the user's table a string? Wouldn't it be better if it were an int because of auto-incrementing things? Also wrt this error:
```
  2) AUTHENTICATION ROUTES
       Auth routes tests: /api/v1/users/
         Should create user on POST requests:

      Uncaught AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 201 but got 400
      + expected - actual

      -400
      +201
      
      at /home/bonface/Projects/wikonnect/server/test/auth.spec.js:54:27
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:797:3)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:990:12)
      at endReadableNT (_stream_readable.js:1204:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
That's caused by:
```
 error: duplicate key value violates unique constraint "users_pkey"
```
Here's a useful ref: https://stackoverflow.com/questions/44901111/duplicate-key-value-violates-unique-constraint-using-knexjs-with-postgresql#44990974

**Comment by BonfaceKilz** [comment]
I think that the tests are failing because of manual inserts on the id_column. I'm not sure though. Here's a related issue: https://github.com/knex/knex/issues/1855
